#ifndef LIBLIVEWIDGETS_GLOBAL_H
#define LIBLIVEWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBLIVEWIDGETS_LIBRARY)
#  define LIBLIVEWIDGETSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBLIVEWIDGETSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBLIVEWIDGETS_GLOBAL_H
